version: '3'

services:
  app: 
    image: 'abh1nav/dockerui:latest'
    ports:
      - '5080:9000'
    networks:
      - my-net
    deploy: 
      mode: replicated
      replicas: 1
networks: 
  my-net:
    driver: overlay