version: '3'

services:
  app: 
    image: 'bitnami/grafana'
    ports:
      - '5080:3000'
    networks:
      - my-net
    deploy: 
      mode: replicated
      replicas: 1
networks: 
  my-net:
    driver: overlay