version: '3'

services:
  app: 
    image: 'hello-world'
    ports:
      - '80:80'
    networks:
      - my-net
    deploy: 
      mode: replicated
      replicas: 1
networks: 
  my-net:
    driver: overlay